apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-ops
  template:
    metadata:
      labels:
        app: support-ops
    spec:
      containers:
      - name: support-ops
        image: quay.io/redhat-user-workloads/konflux-user-support-tenant/chat-bot/user-support@sha256:5355917722f5ff934665fb555b2d75f9f80aec9054922b36865ff662e25a588d
        imagePullPolicy: Always
        env:
        - name: PYTHONPATH
          value: "/app"
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: konflux-support-ops-secrets
              key: SLACK_BOT_TOKEN
        - name: SLACK_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: konflux-support-ops-secrets
              key: SLACK_APP_TOKEN
        - name: JIRA_API_KEY
          valueFrom:
            secretKeyRef:
              name: konflux-support-ops-secrets
              key: JIRA_API_KEY
        - name: JIRA_API_KEY_KONFLUX
          valueFrom:
            secretKeyRef:
              name: konflux-support-ops-secrets
              key: JIRA_API_KEY
        - name: ENABLE_TOKEN_VALIDATION
          value: "true"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
          seccompProfile:
            type: RuntimeDefault
          readOnlyRootFilesystem: true
          runAsNonRoot: true
