apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-ops
  template:
    metadata:
      labels:
        app: support-ops
    spec:
      containers:
      - name: support-ops
        image: quay.io/redhat-user-workloads/konflux-user-support-tenant/chat-bot/user-support@sha256:f896a356fda0efb18015218e28114b5dd6a38cb1da2162ef0aa75b675b66486a
        env:
        - name: PYTHONPATH
          value: "/app"
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: konflux-support-ops-secrets
              key: SLACK_BOT_TOKEN
        - name: SLACK_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: konflux-support-ops-secrets
              key: SLACK_APP_TOKEN
        - name: JIRA_API_KEY
          valueFrom:
            secretKeyRef:
              name: konflux-support-ops-secrets
              key: JIRA_API_KEY
        - name: JIRA_API_KEY_KONFLUX
          valueFrom:
            secretKeyRef:
              name: konflux-support-ops-secrets
              key: JIRA_API_KEY_KONFLUX
        - name: JIRA_API_KEY_RHN
          valueFrom:
            secretKeyRef:
              name: konflux-support-ops-secrets
              key: JIRA_API_KEY_RHN
        - name: JIRA_API_KEY_SP_RHEL
          valueFrom:
            secretKeyRef:
              name: konflux-support-ops-secrets
              key: JIRA_API_KEY_SP_RHEL
        - name: JIRA_API_KEY_TFT
          valueFrom:
            secretKeyRef:
              name: konflux-support-ops-secrets
              key: JIRA_API_KEY_TFT
        - name: JIRA_API_KEY_OSCI
          valueFrom:
            secretKeyRef:
              name: konflux-support-ops-secrets
              key: JIRA_API_KEY_OSCI
        - name: JIRA_API_KEY_RHAI
          valueFrom:
            secretKeyRef:
              name: konflux-support-ops-secrets
              key: JIRA_API_KEY_RHAI
        - name: JIRA_API_KEY_OPENSHIFT_PIPELINES
          valueFrom:
            secretKeyRef:
              name: konflux-support-ops-secrets
              key: JIRA_API_KEY_OPENSHIFT_PIPELINES
        - name: TELCO_PRE_GA_JIRA_TOKEN
          valueFrom:
            secretKeyRef:
              name: konflux-support-ops-secrets
              key: TELCO_PRE_GA_JIRA_TOKEN
        - name: CONVO_PROD_TOKEN
          valueFrom:
            secretKeyRef:
              name: konflux-support-ops-secrets
              key: CONVO_PROD_TOKEN
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: konflux-support-ops-secrets
              key: POSTGRES_HOST
        - name: POSTGRES_HOST_READER_URL
          valueFrom:
            secretKeyRef:
              name: konflux-support-ops-secrets
              key: POSTGRES_HOST_READER_URL
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: konflux-support-ops-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: konflux-support-ops-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: konflux-support-ops-secrets
              key: POSTGRES_PORT
        - name: ENABLE_TOKEN_VALIDATION
          value: "true"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
          seccompProfile:
            type: RuntimeDefault
          readOnlyRootFilesystem: true
          runAsNonRoot: true
