apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: konflux-kyverno

generators:
- kyverno-helm-generator.yaml

patches:
- path: job_patches.yaml
  target:
    group: batch
    kind: Job
    name: konflux-kyverno-migrate-resources
    version: v1
