---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - internal-services
  - openshift-pipelines
  - kargo
  - cert-manager
  - konflux-support-ops
  - konflux-devlake
  - monitoring-workload-logging
