---
apiVersion: v1
kind: ConfigMap
metadata:
  name: konflux-mcp-config
  namespace: konflux-devlake
data:
  OIDC_CLIENT_ID: "cloud-services"
  OIDC_ENABLED: "true"
  OIDC_ISSUER_URL: "https://sso.redhat.com/auth/realms/redhat-external"
  OIDC_OFFLINE_TOKEN_ENABLED: "true"
  OIDC_TOKEN_EXCHANGE_CLIENT_ID: "cloud-services"

